CREATE TABLE `fos_user` (
                            `id` int(11) NOT NULL,
                            `username` varchar(255)  NOT NULL,
                            `username_canonical` varchar(255)  NOT NULL,
                            `email` varchar(255)  NOT NULL,
                            `email_canonical` varchar(255)  NOT NULL,
                            `enabled` tinyint(1) NOT NULL,
                            `salt` varchar(255)  NOT NULL,
                            `password` varchar(255)  NOT NULL,
                            `last_login` datetime DEFAULT NULL,
                            `locked` tinyint(1) NOT NULL,
                            `expired` tinyint(1) NOT NULL,
                            `expires_at` datetime DEFAULT NULL,
                            `confirmation_token` varchar(255)  DEFAULT NULL,
                            `password_requested_at` datetime DEFAULT NULL,
                            `roles` longtext,
                            `credentials_expired` tinyint(1) NOT NULL,
                            `credentials_expire_at` datetime DEFAULT NULL,
                            `type` varchar(255)  NOT NULL,
                            `nombre` varchar(255)  NOT NULL,
                            `apellidos` varchar(255)  DEFAULT NULL,
                            `dni` varchar(255)  DEFAULT NULL,
                            `tipo_documento` enum('nif','nie','cif'),
                            `n_ss` varchar(255)  DEFAULT NULL,
                            `n_cuenta` varchar(255)  DEFAULT NULL,
                            `fecha_nacimiento` date DEFAULT NULL,
                            `direccion` varchar(255)  DEFAULT NULL,
                            `localidad` varchar(255)  DEFAULT NULL,
                            `provincia` varchar(255)  DEFAULT NULL,
                            `cp` varchar(255)  DEFAULT NULL,
                            `pais` varchar(255)  DEFAULT NULL,
                            `telefono` varchar(255)  DEFAULT NULL,
                            `observaciones` varchar(500)  DEFAULT NULL,
                            `slug` varchar(100)  NOT NULL,
                            `id_responsable` int(11) DEFAULT NULL,
                            `sexo` enum('nsnc','mujer','hombre'),
                            `direccion_envio` varchar(255)  DEFAULT NULL,
                            `localidad2` varchar(255)  DEFAULT NULL,
                            `provincia2` varchar(255)  DEFAULT NULL,
                            `cp2` varchar(255)  DEFAULT NULL,
                            `nacionalidad` varchar(255)  DEFAULT NULL,
                            `telf_movil` varchar(255)  DEFAULT NULL,
                            `telf_otro` varchar(255)  DEFAULT NULL,
                            `altura` decimal(10,2) DEFAULT NULL,
                            `talla` int(11) DEFAULT NULL,
                            `medida_pecho` int(11) DEFAULT NULL,
                            `medida_cintura` int(11) DEFAULT NULL,
                            `medida_cadera` int(11) DEFAULT NULL,
                            `calzado` int(11) DEFAULT NULL,
                            `color_ojos` enum('marrones','verdes','azules','nsnc') ,
                            `color_pelo` enum('rubio','moreno','castanio','pelirrojo','otro','nsnc') ,
                            `path_carta_presentacion` tinytext ,
                            `path_cv` tinytext ,
                            `path_cara` tinytext ,
                            `path_medio_cuerpo` tinytext ,
                            `path_cuerpo` tinytext ,
                            `comentarios` varchar(500)  DEFAULT NULL,
                            `exp_congresos` enum('nsnc','si','no') ,
                            `gogo` enum('nsnc','si','no') ,
                            `promociones` enum('nsnc','si','no') ,
                            `exp_traducciones` enum('nsnc','si','no') ,
                            `exp_hosteleria` enum('nsnc','si','no') ,
                            `fiestas_noche` enum('nsnc','si','no') ,
                            `animadores` enum('nsnc','si','no') ,
                            `ferias` enum('nsnc','si','no') ,
                            `patinadora` enum('nsnc','si','no') ,
                            `monitor` enum('nsnc','si','no') ,
                            `seminarios` enum('nsnc','si','no') ,
                            `bailarinas` enum('nsnc','si','no') ,
                            `maquilladora` enum('nsnc','si','no') ,
                            `guardarropa` enum('nsnc','si','no') ,
                            `telemarketing` enum('nsnc','si','no') ,
                            `reponedor` enum('nsnc','si','no') ,
                            `administrativo` enum('nsnc','si','no') ,
                            `sumiller` enum('nsnc','si','no') ,
                            `sin_experiencia` enum('nsnc','si','no') ,
                            `localidad_mov1` varchar(255)  ,
                            `localidad_mov2` varchar(255)  ,
                            `localidad_mov3` varchar(255)  ,
                            `manianas` enum('nsnc','si','no') ,
                            `tardes` enum('nsnc','si','no') ,
                            `noches` enum('nsnc','si','no') ,
                            `findesemana` enum('nsnc','si','no') ,
                            `carnet` enum('nsnc','si','no') ,
                            `vehiculo` enum('nsnc','si','no') ,
                            `desplazamiento` enum('nsnc','si','no') ,
                            `nivel_estudios` enum('sinestudios','primaria','secundaria','profesional','diplomado','licenciado','nsnc'),
                            `est_traduccion` enum('nsnc','si','no') ,
                            `marketing` enum('nsnc','si','no') ,
                            `derecho` enum('nsnc','si','no') ,
                            `est_hosteleria` enum('nsnc','si','no') ,
                            `empresariales` enum('nsnc','si','no') ,
                            `disenio_grafico` enum('nsnc','si','no') ,
                            `relaciones_laborales` enum('nsnc','si','no') ,
                            `turismo` enum('nsnc','si','no') ,
                            `economicas` enum('nsnc','si','no') ,
                            `comunicacion` enum('nsnc','si','no') ,
                            `magisterio` enum('nsnc','si','no') ,
                            `otros_estudios` enum('nsnc','si','no') ,
                            `castellano` enum('nsnc','si','no') ,
                            `catalan` enum('nsnc','si','no') ,
                            `gallego` enum('nsnc','si','no') ,
                            `euskera` enum('nsnc','si','no') ,
                            `ingles` enum('nsnc','si','no') ,
                            `frances` enum('nsnc','si','no') ,
                            `aleman` enum('nsnc','si','no') ,
                            `italiano` enum('nsnc','si','no') ,
                            `portugues` enum('nsnc','si','no') ,
                            `ruso` enum('nsnc','si','no') ,
                            `otros_idiomas` enum('nsnc','si','no') ,
                            `word` enum('nsnc','si','no') ,
                            `excel` enum('nsnc','si','no') ,
                            `access` enum('nsnc','si','no') ,
                            `powerpoint` enum('nsnc','si','no') ,
                            `internet` enum('nsnc','si','no') ,
                            `photoshop` enum('nsnc','si','no') ,
                            `sin_informatica` enum('nsnc','si','no') ,
                            `motivo` longtext ,
                            `status` enum('valido','invalido','incompleto') ,
                            `password_cambiado` tinyint(1),
                            `cambios` longtext ,
                            `lunes_maniana` enum('nsnc','si','no') ,
                            `lunes_tarde` enum('nsnc','si','no') ,
                            `lunes_noche` enum('nsnc','si','no') ,
                            `martes_maniana` enum('nsnc','si','no') ,
                            `martes_tarde` enum('nsnc','si','no') ,
                            `martes_noche` enum('nsnc','si','no') ,
                            `miercoles_maniana` enum('nsnc','si','no') ,
                            `miercoles_tarde` enum('nsnc','si','no') ,
                            `miercoles_noche` enum('nsnc','si','no') ,
                            `jueves_maniana` enum('nsnc','si','no') ,
                            `jueves_tarde` enum('nsnc','si','no') ,
                            `jueves_noche` enum('nsnc','si','no') ,
                            `viernes_maniana` enum('nsnc','si','no') ,
                            `viernes_tarde` enum('nsnc','si','no') ,
                            `viernes_noche` enum('nsnc','si','no') ,
                            `sabado_maniana` enum('nsnc','si','no') ,
                            `sabado_tarde` enum('nsnc','si','no') ,
                            `sabado_noche` enum('nsnc','si','no') ,
                            `domingo_maniana` enum('nsnc','si','no') ,
                            `domingo_tarde` enum('nsnc','si','no') ,
                            `domingo_noche` enum('nsnc','si','no') ,
                            `lopd` enum('nsnc','si','no')  ,
                            `acrobata` enum('nsnc','si','no') ,
                            `actor` enum('nsnc','si','no') ,
                            `bartender` enum('nsnc','si','no') ,
                            `camarero` enum('nsnc','si','no') ,
                            `coctelero` enum('nsnc','si','no') ,
                            `comico` enum('nsnc','si','no') ,
                            `equilibrista` enum('nsnc','si','no') ,
                            `escupefuegos` enum('nsnc','si','no') ,
                            `guitarrista` enum('nsnc','si','no') ,
                            `informatico` enum('nsnc','si','no') ,
                            `logistica` enum('nsnc','si','no') ,
                            `mago` enum('nsnc','si','no') ,
                            `montador` enum('nsnc','si','no') ,
                            `percusionista` enum('nsnc','si','no') ,
                            `pianista` enum('nsnc','si','no') ,
                            `promocion` enum('nsnc','si','no') ,
                            `promotor` enum('nsnc','si','no') ,
                            `relaciones_publicas` enum('nsnc','si','no') ,
                            `saxofonista` enum('nsnc','si','no') ,
                            `speakers` enum('nsnc','si','no') ,
                            `violinista` enum('nsnc','si','no') ,
                            `zancudo` enum('nsnc','si','no') 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `fos_user` (`id`, `username`, `username_canonical`, `email`, `email_canonical`, `enabled`, `salt`, `password`, `last_login`, `locked`, `expired`, `expires_at`, `confirmation_token`, `password_requested_at`, `roles`, `credentials_expired`, `credentials_expire_at`, `type`, `nombre`, `apellidos`, `dni`, `tipo_documento`, `n_ss`, `n_cuenta`, `fecha_nacimiento`, `direccion`, `localidad`, `provincia`, `cp`, `pais`, `telefono`, `observaciones`, `slug`, `id_responsable`, `sexo`, `direccion_envio`, `localidad2`, `provincia2`, `cp2`, `nacionalidad`, `telf_movil`, `telf_otro`, `altura`, `talla`, `medida_pecho`, `medida_cintura`, `medida_cadera`, `calzado`, `color_ojos`, `color_pelo`, `path_carta_presentacion`, `path_cv`, `path_cara`, `path_medio_cuerpo`, `path_cuerpo`, `comentarios`, `exp_congresos`, `gogo`, `promociones`, `exp_traducciones`, `exp_hosteleria`, `fiestas_noche`, `animadores`, `ferias`, `patinadora`, `monitor`, `seminarios`, `bailarinas`, `maquilladora`, `guardarropa`, `telemarketing`, `reponedor`, `administrativo`, `sumiller`, `sin_experiencia`, `localidad_mov1`, `localidad_mov2`, `localidad_mov3`, `manianas`, `tardes`, `noches`, `findesemana`, `carnet`, `vehiculo`, `desplazamiento`, `nivel_estudios`, `est_traduccion`, `marketing`, `derecho`, `est_hosteleria`, `empresariales`, `disenio_grafico`, `relaciones_laborales`, `turismo`, `economicas`, `comunicacion`, `magisterio`, `otros_estudios`, `castellano`, `catalan`, `gallego`, `euskera`, `ingles`, `frances`, `aleman`, `italiano`, `portugues`, `ruso`, `otros_idiomas`, `word`, `excel`, `access`, `powerpoint`, `internet`, `photoshop`, `sin_informatica`, `motivo`, `status`, `password_cambiado`, `cambios`, `lunes_maniana`, `lunes_tarde`, `lunes_noche`, `martes_maniana`, `martes_tarde`, `martes_noche`, `miercoles_maniana`, `miercoles_tarde`, `miercoles_noche`, `jueves_maniana`, `jueves_tarde`, `jueves_noche`, `viernes_maniana`, `viernes_tarde`, `viernes_noche`, `sabado_maniana`, `sabado_tarde`, `sabado_noche`, `domingo_maniana`, `domingo_tarde`, `domingo_noche`, `lopd`, `acrobata`, `actor`, `bartender`, `camarero`, `coctelero`, `comico`, `equilibrista`, `escupefuegos`, `guitarrista`, `informatico`, `logistica`, `mago`, `montador`, `percusionista`, `pianista`, `promocion`, `promotor`, `relaciones_publicas`, `saxofonista`, `speakers`, `violinista`, `zancudo`) VALUES (2, 'test', 'test', 'test@gmail.com', 'test@gmail.com', 0, 'go9oefum1xwsoowk0s8sgcwwkgc0wkc', 'USUARIO_DESHABILITADO', '2017-04-04 19:15:04', 0, 0, NULL, 'P0au32kZHM4sVC2H4B2A5PWlcfQzqh9C3Q01f8MnSE8', '2015-01-17 11:21:59', 'a:11:{i:0;s:9:\"ROLE_USER\";i:1;s:10:\"ROLE_STOCK\";i:2;s:16:\"ROLE_ADMIN_STOCK\";i:3;s:21:\"ROLE_SUPERADMIN_STOCK\";i:4;s:21:\"ROLE_EVENTOS_EMPLEADO\";i:5;s:12:\"ROLE_EVENTOS\";i:6;s:23:\"ROLE_SUPERADMIN_EVENTOS\";i:7;s:18:\"ROLE_ADMIN_EVENTOS\";i:8;s:23:\"ROLE_EVENTOS_RESP_PAGOS\";i:9;s:26:\"ROLE_ADMIN_EVENTOS_CLIENTE\";i:10;s:28:\"ROLE_ADMIN_EVENTOS_PROVEEDOR\";}', 0, NULL, 'eventos_empleado', 'Usuario', 'Para pruebas', '', 'nif', '', '', '1984-03-05', '', '', '', '', '', '911223344', '', 'test', NULL, 'nsnc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'nsnc', 'nsnc', NULL, NULL, NULL, NULL, NULL, NULL, 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', NULL, NULL, NULL, 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', NULL, NULL, 0, NULL, 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'si', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc', 'nsnc');
